NAME	= dream_job
CC		= c++
CFLAGS	= -std=c++17 -Wall -Wextra -Werror

all: $(NAME)

$(NAME):
	$(CC) $(CFLAGS) $(NAME).cc -o $(NAME)

clean:
	@rm -rf $(NAME)

fclean: clean

re : fcelan all

.PHONY: all clean fclean re