NAME	= megaphone
CC		= c++
CFLAGS	= -std=c++98 -Wall -Wextra -Werror

all: $(NAME)

$(NAME):
	$(CC) $(CFLAGS) megaphone.cpp -o $(NAME)

clean:
	@rm -rf $(NAME)

fclean: clean

re : fcelan all

.PHONY: all clean fclean re